#!/bin/bash
# ============================================================
# 008_seed_cordis.sh
# Automatic CORDIS + Patent mock-data seed for first DB init.
# Executed by PostgreSQL docker-entrypoint-initdb.d on first start.
# ============================================================
set -euo pipefail

MOCK_DIR="/docker-entrypoint-initdb.d/mock_data"
DB="${POSTGRES_DB:-ti_radar}"
USER="${POSTGRES_USER:-tip_admin}"

# ------------------------------------------------------------------
# Guard: only seed if cordis_schema.projects is empty
# ------------------------------------------------------------------
ROW_COUNT=$(psql -U "$USER" -d "$DB" -tAc \
    "SELECT COUNT(*) FROM cordis_schema.projects;" 2>/dev/null || echo "0")

if [ "$ROW_COUNT" -gt 0 ]; then
    echo "008_seed_cordis: projects table already has $ROW_COUNT rows — skipping seed."
    exit 0
fi

# Verify mock data directory exists
if [ ! -d "$MOCK_DIR" ]; then
    echo "008_seed_cordis: mock data directory $MOCK_DIR not found — skipping seed."
    exit 0
fi

echo "008_seed_cordis: seeding CORDIS + patent mock data …"

# ------------------------------------------------------------------
# Helper: allow explicit IDs on GENERATED ALWAYS AS IDENTITY columns
# ------------------------------------------------------------------
# Tables with GENERATED ALWAYS AS IDENTITY need to be temporarily
# switched to GENERATED BY DEFAULT so that \copy can insert the
# original IDs from the CSV (required to keep FK references intact).
# After loading, the identity sequence is reset to MAX(id)+1.
# ------------------------------------------------------------------

psql -U "$USER" -d "$DB" -v ON_ERROR_STOP=1 <<'EOSQL'
-- Allow explicit IDs during seed
ALTER TABLE cordis_schema.organizations
    ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE cordis_schema.publications
    ALTER COLUMN id SET GENERATED BY DEFAULT;
ALTER TABLE cordis_schema.euroscivoc
    ALTER COLUMN id SET GENERATED BY DEFAULT;
EOSQL

# ------------------------------------------------------------------
# 1. EuroSciVoc taxonomy (must come before project_euroscivoc)
#    Self-referencing FK is DEFERRABLE INITIALLY DEFERRED, so we
#    wrap in a transaction so all rows are visible at commit time.
# ------------------------------------------------------------------
echo "  [1/6] Loading EuroSciVoc taxonomy …"
psql -U "$USER" -d "$DB" -v ON_ERROR_STOP=1 <<EOSQL
BEGIN;
SET CONSTRAINTS cordis_schema.fk_euroscivoc_parent DEFERRED;
\copy cordis_schema.euroscivoc(id, code, label_en, label_de, parent_code, level) FROM '${MOCK_DIR}/euroscivoc.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');
COMMIT;
EOSQL

# ------------------------------------------------------------------
# 2. CORDIS projects (natural key, no identity issue)
# ------------------------------------------------------------------
echo "  [2/6] Loading CORDIS projects (4,814 rows) …"
psql -U "$USER" -d "$DB" -v ON_ERROR_STOP=1 <<EOSQL
\copy cordis_schema.projects(id, framework, title, acronym, objective, keywords, start_date, end_date, total_cost, ec_max_contribution, funding_scheme, status, topics, legal_basis) FROM '${MOCK_DIR}/projects.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');
EOSQL

# ------------------------------------------------------------------
# 3. CORDIS organizations (FK -> projects)
# ------------------------------------------------------------------
echo "  [3/6] Loading CORDIS organizations (4,034 rows) …"
psql -U "$USER" -d "$DB" -v ON_ERROR_STOP=1 <<EOSQL
\copy cordis_schema.organizations(id, organisation_id, project_id, name, short_name, country, city, role, activity_type, sme, ec_contribution, total_cost) FROM '${MOCK_DIR}/organizations.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');
EOSQL

# ------------------------------------------------------------------
# 4. CORDIS publications (FK -> projects)
#    CSV includes search_vector but the BEFORE INSERT trigger will
#    regenerate it, so we load it anyway (harmless).
# ------------------------------------------------------------------
echo "  [4/6] Loading CORDIS publications (17,900 rows) …"
psql -U "$USER" -d "$DB" -v ON_ERROR_STOP=1 <<EOSQL
\copy cordis_schema.publications(id, project_id, title, authors, journal, publication_date, doi, open_access, search_vector) FROM '${MOCK_DIR}/publications.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');
EOSQL

# ------------------------------------------------------------------
# 5. Project-EuroSciVoc junction (composite PK, no identity)
# ------------------------------------------------------------------
echo "  [5/6] Loading project-EuroSciVoc mappings (3,249 rows) …"
psql -U "$USER" -d "$DB" -v ON_ERROR_STOP=1 <<EOSQL
\copy cordis_schema.project_euroscivoc(project_id, euroscivoc_id) FROM '${MOCK_DIR}/project_euroscivoc.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');
EOSQL

# ------------------------------------------------------------------
# 6. EPO patents (if CSV exists)
# ------------------------------------------------------------------
if [ -f "${MOCK_DIR}/patents.csv" ]; then
    echo "  [6/6] Loading EPO patents (6,019 rows) …"
    psql -U "$USER" -d "$DB" -v ON_ERROR_STOP=1 <<EOSQL
ALTER TABLE patent_schema.patents
    ALTER COLUMN id SET GENERATED BY DEFAULT;

\copy patent_schema.patents(id, publication_number, country, doc_number, kind, title, publication_date, publication_year, family_id, applicant_names, applicant_countries, cpc_codes, ipc_codes, filing_date) FROM '${MOCK_DIR}/patents.csv' WITH (FORMAT csv, HEADER true, ENCODING 'UTF8');

-- Reset patent identity sequence
SELECT setval(
    pg_get_serial_sequence('patent_schema.patents', 'id'),
    COALESCE((SELECT MAX(id) FROM patent_schema.patents), 0) + 1,
    false
);

-- Restore GENERATED ALWAYS
ALTER TABLE patent_schema.patents
    ALTER COLUMN id SET GENERATED ALWAYS;

-- Populate patent_cpc junction from the cpc_codes array for materialized views
INSERT INTO patent_schema.patent_cpc (patent_id, cpc_code, pub_year)
SELECT DISTINCT
    sub.id,
    sub.cpc_code,
    sub.publication_year
FROM (
    SELECT
        p.id,
        LEFT(unnest(p.cpc_codes), 4) AS cpc_code,
        p.publication_year
    FROM patent_schema.patents p
    WHERE p.cpc_codes IS NOT NULL
      AND array_length(p.cpc_codes, 1) > 0
) sub
WHERE sub.cpc_code ~ '^[A-HY][0-9]{2}[A-Z]?$'
ON CONFLICT DO NOTHING;
EOSQL
else
    echo "  [6/6] patents.csv not found — skipping patent seed."
fi

# ------------------------------------------------------------------
# Reset identity sequences and restore GENERATED ALWAYS
# ------------------------------------------------------------------
echo "  Resetting identity sequences …"
psql -U "$USER" -d "$DB" -v ON_ERROR_STOP=1 <<'EOSQL'
-- Reset sequences to MAX(id)+1
SELECT setval(
    pg_get_serial_sequence('cordis_schema.organizations', 'id'),
    COALESCE((SELECT MAX(id) FROM cordis_schema.organizations), 0) + 1,
    false
);
SELECT setval(
    pg_get_serial_sequence('cordis_schema.publications', 'id'),
    COALESCE((SELECT MAX(id) FROM cordis_schema.publications), 0) + 1,
    false
);
SELECT setval(
    pg_get_serial_sequence('cordis_schema.euroscivoc', 'id'),
    COALESCE((SELECT MAX(id) FROM cordis_schema.euroscivoc), 0) + 1,
    false
);

-- Restore GENERATED ALWAYS on identity columns
ALTER TABLE cordis_schema.organizations
    ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE cordis_schema.publications
    ALTER COLUMN id SET GENERATED ALWAYS;
ALTER TABLE cordis_schema.euroscivoc
    ALTER COLUMN id SET GENERATED ALWAYS;
EOSQL

# ------------------------------------------------------------------
# Refresh all materialized views in cross_schema
# ------------------------------------------------------------------
echo "  Refreshing materialized views …"
psql -U "$USER" -d "$DB" -v ON_ERROR_STOP=1 <<'EOSQL'
-- Patent-based MVs (will be empty if no patents loaded, but must be refreshed)
REFRESH MATERIALIZED VIEW cross_schema.mv_patent_counts_by_cpc_year;
REFRESH MATERIALIZED VIEW cross_schema.mv_cpc_cooccurrence;
REFRESH MATERIALIZED VIEW cross_schema.mv_yearly_tech_counts;
REFRESH MATERIALIZED VIEW cross_schema.mv_top_applicants;
REFRESH MATERIALIZED VIEW cross_schema.mv_patent_country_distribution;

-- CORDIS-based MVs
REFRESH MATERIALIZED VIEW cross_schema.mv_project_counts_by_year;
REFRESH MATERIALIZED VIEW cross_schema.mv_cordis_country_pairs;
REFRESH MATERIALIZED VIEW cross_schema.mv_top_cordis_orgs;
REFRESH MATERIALIZED VIEW cross_schema.mv_funding_by_instrument;
EOSQL

# ------------------------------------------------------------------
# Summary
# ------------------------------------------------------------------
TOTAL=$(psql -U "$USER" -d "$DB" -tAc "
    SELECT
        (SELECT COUNT(*) FROM cordis_schema.projects) +
        (SELECT COUNT(*) FROM cordis_schema.organizations) +
        (SELECT COUNT(*) FROM cordis_schema.publications) +
        (SELECT COUNT(*) FROM cordis_schema.euroscivoc) +
        (SELECT COUNT(*) FROM cordis_schema.project_euroscivoc) +
        (SELECT COUNT(*) FROM patent_schema.patents);
")

echo "008_seed_cordis: done — $TOTAL total rows seeded (quantum computing mock data)."
